# Generated by Django 6.0.3 on 2026-03-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="password",
            field=models.CharField(default=123456789, max_length=128),
            preserve_default=False,
        ),
    ]
